name: Build Screeps Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Screeps version to build'
        required: false
        default: 'latest'

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/screeps
      VERSION: ${{ github.event.inputs.version || 'latest' }}
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Authentication
      run: docker login --username '${{ secrets.DOCKER_HUB_USERNAME }}' --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
    - name: Pull the Latest Built
      run: docker pull "${DOCKER_IMAGE}:latest" || true
    - name: Build the Docker Image
      run: docker build --build-arg "version=${VERSION}" --cache-from "${DOCKER_IMAGE}:latest" --file 'Dockerfile' --pull --tag "${DOCKER_IMAGE}:${VERSION}" .
    - name: Smoke Test
      run: docker run -i --rm "${DOCKER_IMAGE}:${VERSION}" npx screeps
    - name: Push the Docker image
      run: docker push "${DOCKER_IMAGE}:${VERSION}"
      
  build-alpine:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/screeps
      VERSION: ${{ github.event.inputs.version || 'latest' }}
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Authentication
      run: docker login --username '${{ secrets.DOCKER_HUB_USERNAME }}' --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
    - name: Pull the Latest Built
      run: docker pull "${DOCKER_IMAGE}:alpine" || true
    - name: Build the Docker Image
      run: |
        TAG="${DOCKER_IMAGE}:alpine-${VERSION}"
        if [ "${VERSION}" = 'latest' ]; then
          TAG="${DOCKER_IMAGE}:alpine"
        fi
        docker build --build-arg "version=${VERSION}" --cache-from "${DOCKER_IMAGE}:alpine" --file 'Dockerfile-alpine' --pull --tag "${TAG}" .
    - name: Smoke Test
      run: |
        TAG="${DOCKER_IMAGE}:alpine-${VERSION}"
        if [ "${VERSION}" = 'latest' ]; then
          TAG="${DOCKER_IMAGE}:alpine"
        fi
        docker run -i --rm "${TAG}" npx screeps
    - name: Push the Docker image
      run: |
        TAG="${DOCKER_IMAGE}:alpine-${VERSION}"
        if [ "${VERSION}" = 'latest' ]; then
          TAG="${DOCKER_IMAGE}:alpine"
        fi
        docker push "${TAG}"
